### ISSUE TITLE
Delete extra code

### ISSUE THREAD

**Issue by April6804** [callyhazzard/Lists#1]
https://github.com/callyhazzard/Lists/blob/f4c029fb01892ec5a62273d7d7e72c7852556ba9/index.html#L10
Hi,
I know that in Atom, you typed in html and hit tab, but the next step would be entering code inside of the body tags so it matches the book. We don't want to have two sets of html, head, or body tags.
Make sure to delete lines 2 through 10.

**Comment by callyhazzard** [comment]
I think I resolved this! Thank You
